### PR TITLE
Pull request to keep things in sync

### PR DESCRIPTION
**Pull request by david-macmahon**
Mostly benign changes related to packaging and cuda_correlator benchmarking tool.

### CODE REVIEW

**Comment by maddyscientist** [comment]
@david-macmahon somehow I managed to go a a year without noticing this.  Is this still relevant, shall I merge?

**Comment by david-macmahon** [comment]
That would be great!  It would also be nice to update the README with details about building for the various generations of GPU, but I guess I can add that as a separate feature request.

**Comment by maddyscientist** [comment]
@david-macmahon Thanks for the pull and sorry for the aeonic response time.  Feel free to file more with respect to gpu architectures.

Is there any urgent at your end for me to clean up the dp4 branch and merge this in, eh are you folks using pascals at all and want to use the native 8-bit multipliers?

**Comment by jack-h** [comment]
In the spirit of slow response time -- we're about to try a GTX1080-based HERA correlator, so anything to smooth that process would be appreciated. We're still building antennas though, gonna be bandwidth limited for a while...

**Pull request merged**
